### ISSUE TITLE
Filename UUID check should be a warning

### ISSUE THREAD

**Issue by remia** [Ymagis/ClairMeta#103]
Update the default check profile to consider `check_assets_cpl_filename_uuid` as a warning.

**Comment by Yujing199603** [comment]
Hi, we just encountered this! The filename of an MXF file had a different UUID to the UUID listed in the ASSERMAP - but this should just be a warning as there are many DCPs where the UUID specified in the ASSETMAP is not included in the filename?

**Comment by remia** [comment]
Yes this should be a warning indeed.

But it's not as frequent as you might think because the check only fails when a UUID is actually correctly extracted from the filename and this UUID don't match the asset UUID from the Assetmap, eg. a file named REEL_01_VIDEO.mxf would not make the test fails !

Hope that's clear, I plan to release a new stable version soon now that we have unittest ready.

**Comment by kieranjol** [comment]
Yup,we have some that are some version of CONTENT_TITLE.mxf and these are
not flagged.

**Comment by remia** [comment]
Adressed in #105
