### ISSUE TITLE
bintray distro repo name typo, ubuntu rtful should be ubuntu artful

### ISSUE THREAD

**Issue by LeoWinterDE** [Ymagis/ClairMeta#13]
Hi,
the bintray repo (https://dl.bintray.com/ymagis/Clairmeta/dists/) has a distro name typo, Ubuntu artful (17.10) not Ubuntu rtful.

Thanks for this awesome project/tool.

**Comment by remia** [comment]
Thanks for this report !

Indeed there is a typo in the distro name but I have no idea why for the moment, I think this is generated automatically by bintray when we upload package via travis but maybe I'm missing something. We'll investigate this.

Do you know if this was the case for precedent versions ?

**Comment by LeoWinterDE** [comment]
The previous versions work fine and none of your last commits changed anything on the repo name as far i can see.

Seems like a @bintray bug. https://github.com/alanfranz/docker-rpm-builder/issues/56

**Comment by remia** [comment]
Thanks for finding this.

I checked the travis build log and didn't found anything with a typo in it, all the calls to bintray API specify the correct distribution name : artful. Will be monitoring, maybe we'll have to trigger a new build when bintray fix this. Anything urgent on your side ?

**Comment by LeoWinterDE** [comment]
Magically broken and fixed by @bintray / @JFrogDev, without any information at all.
What a great service... maybe we'll be looking for alternatives in the long run.

**Comment by remia** [comment]
Thanks for the update Leo !

Maybe yes, it's the first time I use Bintray and I'm pretty happy for now but we'll see in the long run as you say. The sad thing is that there is no support for OSS user I think, I only found a link to bintray stackoverflow topics when searching.
