### ISSUE TITLE
Clairmeta fails on Fade{Up,Down}Time attribute in HH:MM:SS:TTT or HH:MM:SS.sss format

### ISSUE THREAD

**Issue by matmat** [Ymagis/ClairMeta#131]
This is for Interop/Cinecanvas subtitles.

I have a subtitle file with the following:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<DCSubtitle Version="1.0">
(...)
<Subtitle SpotNumber="976" TimeIn="00:00:08:115" TimeOut="00:00:14:083" FadeUpTime="00:00:02:000" FadeDownTime="00:00:01:000">
```

Clairmeta fails with:
```
2019-12-02 05:56:15,733 - Clairmeta - INFO - Error(s) :
	check_subtitle_cpl_st_timing - Check unknown error
Traceback (most recent call last):
  File "/home/mhm/ClairMeta/clairmeta/dcp_check_base.py", line 118, in run_check
    check_res = func(*args)
  File "/home/mhm/ClairMeta/clairmeta/dcp_check_subtitle.py", line 376, in check_subtitle_cpl_st_timing
    if f_s and f_s > dur:
TypeError: '>' not supported between instances of 'str' and 'int'
```

TI's Cinecanvas spec v1.0 says for both the `FadeUpTime` (and similairly for `FadeDownTime`) of the `Subtitle` element:

> _The time that it takes to bring a subtitle fully on screen. A subtitle begins to appear at the time specified in the **TimeIn** attribute, and fades in over the time specified in this attribute. **FadeUpTime** is in the format TTT, where TTT = ticks. A “tick” is defined as 4 msec and has a range of 0 to 249. This definition of tick was chosen because it will allow frame accurate timing at multiple frame rates, without specifying the display frame rate in the subtitle file._
> 
> _Default FadeUpTime = 20 (this is 80 msec)_

CineCanvas spec v1.1 adds the following text:

> _For fade times greater than one second, the full time format of HH:MM:SS:TTT or HH:MM:SS.sss must be used. See the attribute description for **TimeIn** or **TimeOut** for the definition of these formats. **FadeUpTime** will be limited to a maximum of 8 seconds. Any time greater than this will be replaced with the max time of 8 seconds._

And changes the last sentance to (emphasis mine):

> _This definition of **time** was chosen because it will allow frame accurate timing at multiple frame rates, without specifying the display frame rate in the subtitle file._

Strictly speaking my subtitle file above does not validate (because it specifies `<DCSubtitle Version="1.0">`), but maybe handle this case more gracefully?

**Comment by remia** [comment]
Hey @matmat,

Is there any chance you can provide the DCP XML files including subtitles obviously to check what is happening there ? I did a quick check of the parsing function and it seems to be handling the different subtitles format well so I guess there is something at a higher level going on.

**Comment by matmat** [comment]
Hi @remia! XML files shared via email. Let me know if you need anything else.

**Comment by remia** [comment]
I did a quick fix here, #132 .

**Comment by matmat** [comment]
Thanks for the quick fix! And sorry for the wrong analysis of this bug.

But wrt the different features  between DCSubtitle v1.0 and v1.1, should these be checked? Should I start a new issue about this?

**Comment by remia** [comment]
Is the difference only on the 8secs maximum fade duration ? I think this would probably raise a warning because the specs says the duration should be automatically truncated to the maximum. In any case I guess a dedicated Issue for this could be clearer.

Can we close this issue now if you confirm the fix works for you ?

Thanks !

**Comment by matmat** [comment]
There are some other differences as well between DCSubtitle v1.0 and v1.1. I will compile them and start a new issue.

This issue can be closed. Thanks for the fix!
