### ISSUE TITLE
Ubuntu 20.04 LTS support

### ISSUE THREAD

**Issue by EliaOrselli** [Ymagis/ClairMeta#142]
clairmeta seems not compatible with ubuntu 20.04 as python 3.6 is outdated

**Comment by remia** [comment]
Thanks for the report @EliaOrselli , we'll need to build ClairMeta for 20.04 indeed.

**Comment by kieranjol** [comment]
Is there much if anything to do to upgrade to work with python3.8 though? Is the real issue just installing all of the dependencies like asdcplib and also adding focal to the apt installer list?

**Comment by remia** [comment]
Indeed, I tried to install clairmeta on focal and it worked (except for asdcplib dependency that don't get installed).

There might be a bit of work to rebuild all the packages specifically for focal because we use `py2deb` for that and it don't seems to work on python3.8 anymore, have to find an alternative probably.

**Comment by EliaOrselli** [comment]
> In the mean time we can of course build just asdcplib and upload it to the repository.

It would be very useful (at least for me 😄 ). Otherwise a text procedure for build asdcplib would be enough

**Comment by remia** [comment]
We are currently stuck while waiting for `py2deb` upgrade to support python 3.8, at least for the python packages generation.

I could still throw an updated asdcplib package to the bintray repository but building is quite simple, here a sample Dockerfile that does that https://gist.github.com/remia/01078c8374af6fb277cc268f4adf9b38, let me know if that works for you.

**Comment by remia** [comment]
Noting that moving forward, we will not support Debian package anymore and just release the python library. An example of environment setup for Ubuntu can be seen in Github Action workflow file.
