### ISSUE TITLE
Enhance check function to incorporate aspects of SMPTE RDD 52

### ISSUE THREAD

**Issue by jamiegau** [Ymagis/ClairMeta#150]
WIth the work behind SMPTE with RDD-52, best practices for DCP creation.
(Note, as of this date, the RDD-52 is in review and expected to become available in weeks)
see: [https://kws.smpte.org/higherlogic/ws/public/projects/616/details](https://kws.smpte.org/higherlogic/ws/public/projects/616/details)

I think it would be a great idea to attempt to codify, where possible, these practices into WARNINGs that will be produced when using this too to check a DCP.  I would also suggest these warning specifically indicate they are evaluated based on SMPTE-RDD-52 as to drive those interested to the source of truth for these WARNINGS.

**Comment by remia** [comment]
Thanks for the heads-up @jamiegau, I have not seen this document yet but it seems like something that would be great to have warnings for, I'll try to watch for the publish version.

**Comment by jamiegau** [comment]
Update,  DRR 52 has been released, and is slated to be free to obtain. (Thank you SMPTE).
Once I have a path to getting the document I will post, as I expect we all want to spend a night reviewing it.

**Comment by matmat** [comment]
Thanks for the update @jamiegau ! RDD 52 is now freely available here: https://ieeexplore.ieee.org/document/9161348

**Comment by remia** [comment]
Thanks to @jamiegau to remind this, we should probably prioritise check implementation.

Looks like a good candidate would be Section 8.3.1 (originally though ClairMeta was already performing this check):

> If a MainSubtitle timed text track is present on any reel, a MainSubtitle timed text track shall be
> present on all reels. If (1) or more ClosedCaption timed text track(s) are present on any reel, the same
> number of ClosedCaption timed text tracks shall be present on all reels.

**Comment by remia** [comment]
Closing this, will need to open specific check request to focus discussion on specific topics from the RDD.

Thanks.
