### ISSUE TITLE
Improve progress callback

### ISSUE THREAD

**Issue by remia** [Ymagis/ClairMeta#154]
Seeings as your kicking around in that code.
Another small extra I would like is for ..
`def  console_progress_bar(file_path, progress, elapsed, done)`
be enhanced to have
`def console_progress_bar(file_path, progress_dcp, dcp_size, progress_file, file_size, elapsed, done)`
So you can display overall progress, file progress and ETA for completion based on how long its been taking to process data up until that time.

_Originally posted by @jamiegau in https://github.com/Ymagis/ClairMeta/issues/152#issuecomment-667939856_

**Comment by jamiegau** [comment]
Note, I addressed this implementation in the following pull request,
#157 
This version will display two different complete percentages.  One for the full DCP and one for the current file.

**Comment by remia** [comment]
Hey @jamiegau,

Could you try to keep only the changes to the progress callback in that PR so that I can start testing it ? It currently have fix for subtitles related errors that I think are not definitive yet so they should probably lives in their own PR.

Thanks for the contribution !

**Comment by jamiegau** [comment]
I have only ever written software for my own needs.
I am hopping getting involved in helping here will help with my code quality and working with others..

Can I ask,  I take it,  I fork the repo..
then create a branch for each issue I want to work on, and then apply that branch as a pull request against a specific  bug/feature. (This is how I have noticed in helping on this project.)
I am new to using git like this.
I will follow this path going forward..

**Comment by remia** [comment]
Yes that sounds good.

You can even use interactive rebase and force push to update the PR in place but's that's a little more involved. As you already closed the PR, I'll just wait for the new one.

**Comment by remia** [comment]
Just updating what was discussed:
*  Check if the callback event firing rate affects performance
*  Check if and how you would implement an ETA for the global DCP hash progression with the current system

**Comment by jamiegau** [comment]
Yes, in regards to updating the progress feature.

**Comment by remia** [comment]
Merged in #162
