### ISSUE TITLE
Report Mode Feature Request: -report/-report_out_file to generate more detailed output.

### ISSUE THREAD

**Issue by jamiegau** [Ymagis/ClairMeta#156]
Hi,
ClaieMeta checks for quite a lot of issues.  It's very impressive.
And I am especially please we now have an open source tool to QC DCPs for problems. (Thats easy to install and use compared to others)
I would like to see the tool updated to generate a QC-Report type result.  For example..

```
python3 -m clairmeta.cli check -type dcp -qc_report DCP_DIR
clairmeta version: X.XX

base CHECK: PASS

cpl CHECK: PASS

am CHECK: PASS

isdcf_dcnc CHECK: WARNING
WARNING:check_dcnc_compliance
ContentTitle must have 12 parts, 11 found
Field Studio not found in ContentTitle

atmos CHECK: NOT_APPLICABLE
.
.
----------------------
QC acceptance: PASS

```
This is especially important in accepting DCPs into some circuits/cinemas, having a tool to pre-submission-check DCPs before they are submitted by random content producers who are making ads or small film festival content.  It's common for non DCP experienced production companies to take on such work and leave the creation of the DCP to the last minute and just grab whatever software they can find to do a DCP.  It would be good to have a free tool to utilise in asset delivery requirements those accepting the DCP can point them at.
i.e. When submitting your DCP, please supply clairmeta QC_REPORT as part of your submission..  Obviously if they are not going to submit the DCP until it passes the QC tool.

The tool, should produce a type of report as listed above, and if a specific check_plugin has issues, it will list them and result in a WARNING or FAIL based on the result of the issue.

The version of the clairmeta version should be part of the report as extra features may come down the line for which a older version of he software does not yet implement.

I have not yet look too deeply into the code, but it appears this type of feature may not be that difficult to add to the implementation.

I will admit, the tool in its current form still is very useful and does archive this outcome, but it does not have the gravitas or specific feel of being as powerful and complete as it is.  Naming all the checks in the report would be far more visceral and hold more weight in how useful this tool really is to the general community that utilises DCPs.

Please comment on this addition and "use model" of the tool.  I am keen to hear others feedback.

**Comment by jamiegau** [comment]
I expect many of us have had time to check out the SMPTE RDD 52 document, now made freely downloadable on
[https://ieeexplore.ieee.org/document/9161348](https://ieeexplore.ieee.org/document/9161348)

This is great to see as its refining to a detailed level what is acceptable for wider release DCP creation.  Also great for film festivals who don't want to spend as much money on repacking DCP..  Specify it must pass clarmeta check before it can be accepted puts making (Costs) a good DCP back on the film maker.

My first reaction would be to add a reasonable amount of RDD52 specifics to clairmeta..  but after reading, I would assume, not that I have looked over all the code, that many of the specifics are already checked for by clairmeta already.

This comes back to this discussion.  Currently clairmeta only reports/prints out anything if it fails a specific test.  There is no real way to see, via its output, what checks have been performed.  This is a considerable floor to me as, if a DCP is in an archive, for example, and with it a clairmeta report was created against it at the time it was archived, there is no way to see what tests were applied at that time.  Just it was OK.  That's not very useful.
Clairmeta will evolve and more tests will likely be added.

After some consideration, I think it is quite important that we add a VERBOSE option at the very least that prints out the test applied, Pass or Fail.

This then comes to how we incorporate RDD 52 tests.    Do we add it as a module, of add tests to specific parts of the code that deal with RDD52 specific tests..  i.e. in subtitles, picture etc.   I would assume we add it to already existing sections of the code.  Where checks that mirror the RDD52 requirements already exist, we modify the error reported to reference the RDD52 document.

**Comment by remia** [comment]
Thanks for opening the discussion @jamiegau.

For context, when we made ClairMeta at Ymagis, we already had another companion application for mastering related things and that tool was responsible for generating this kind of report. For that we used a simple HTML / CSS page and template expansion to fill in the report. We chose not to add it to ClairMeta source code because of the added dependencies and complexity that's not really wanted by everyone.

That's to say it should be relatively easy to implement it already as almost all the informations are already present in the report generated (using the Python API). One thing missing, but probably one liner, is to add the check that succeeded. 

Note that you can easily add the checks description and reference (notice that most check have in their docstring a reference section to source the actual related standard / specification) by reading the docstring programmatically from python (in fact that's what we did).

I may look at it further when I have more time, but for now I won't be able to help with making this report. However I can help by adding any missing piece of information that's needed to generate it.

PS: I didn't get the time to look at RDD 52 yet, but yes, we will add those missing check in their respective module and document where they comes from in the docstring as already done.

**Comment by jamiegau** [comment]
I am and we all should be greatly appreciative to Ymagis for offering this to the public.
Considering ymagis had a vision and specific use model for the tool, I think the best way to approach this is to add a argument flag that adds this functionality as so its default use stays the same. (Apart from upgrades, additions fixes)

Today I had a reasonable look at the code. `dcp_check_base.py` mainly. On this topic, after looker through it..
I noticed 543 checks in the resulting list `self.check_executions`, then it looks though the list for the type of result and ads ERRORS, WARNING, to self.check_report[ ERROR, WARNING, INFO, SILENT ]

```
def make_report(self):
        """ Check report generation. """
        self.check_report = {
            'ERROR': [],
            'WARNING': [],
            'INFO': [],
            'SILENT': []
        }

        for c in self.find_check_failed():     <-- only add check failed into self.check_report 
            level = self.find_check_criticality(c.name)
            self.check_report[level].append((c.name, c.msg))

        check_unique = set([c.name for c in self.check_executions])
        self.check_elapsed = {}
        self.total_time = 0
        self.total_check = len(check_unique)

        for name in check_unique:
            execs = [c.seconds_elapsed
                     for c in self.check_executions if c.name == name]
            elapsed = sum(execs)
            self.total_time += elapsed
            self.check_elapsed[name] = elapsed
```
This appears to go through and populate `self.check_report`.
I find this a little confusing as why do you not add all PASSED checks to INFO?  
And what is suppressed for..  (I imagine those not performed due to the checking profile supplied?)

Could you expand on the purpose here.  What is the INFO list suppose to represent?

In the end, why not just expose `self.check_executions` in the API?

I could understand this portion of the code was mainly written for passing to the `dump_report()` function.

My reaction of reviewing this code is to ad the '-report' flag.
Add passed checks to `self.check_report['INFO']` in `make_report(self)`,
Update dump_report() to accept check for the `-report` flag and if present, add output for all the items found in  `self.check_report['INFO']`

I'll create a new issue regarding CPL errors i also find confusing..

**Comment by remia** [comment]
> I noticed 543 checks in the resulting list self.check_executions

Some checks are repeated for multiple assets, and that's causing the list to be larger that the actual number of unique checks ClairMeta typically perform. One way to find out the actual number by wrapping the list of names in a `set`.

> I find this a little confusing as why do you not add all PASSED checks to INFO?

INFO was supposed to be an "error" level below warning, agreed that it serve no purpose at the moment and we could use it to store all succeeded checks.

> In the end, why not just expose self.check_executions in the API?

Could be the easiest and more flexible way, yes, this list already provide more information with eg. check processing times. We could add even more informations, eg. on which asset the check was performed (if applicable), the docstring of the check, etc.

**Comment by remia** [comment]
Missed one question.

> And what is suppressed for.. (I imagine those not performed due to the checking profile supplied?)

Yes, this correspond to check that were bypassed using the profile `bypass` key.

**Comment by remia** [comment]
#167 is addressing part of the issue by providing a more complete report object, from where you should be able to build a complete report. Let me know if that address your immediate concerns.

**Comment by remia** [comment]
Should we close this ?

**Comment by jamiegau** [comment]
Yes,
You have addressed this from my perspective.
I am working on the online tool still.  I have the interactive version done but for likely bugs to be discovered.
I am currently working on making a HTML based Emailable version that can be exported from the online interactive tool.
Regenerating the interactive graphs as images that can be embedded into an Email.  Based on the draft one I sent you a while ago for Clairmeta, but now adding CPL-structure, Video-bitrate, audio waveforms, loudness analysis images. 

Once I am happy with that I will implement the latest Clairmeta version with recent upgrades and fixes.

Rami, please go to https://admin.d-cine.net and request an account under Research user.  I need to test that part of the website to.  Need to make it as easy as possible to manage/automate considering tis free to use..

Thanks,
James
