### ISSUE TITLE
Should we consider dropping Python2 support ?

### ISSUE THREAD

**Issue by remia** [Ymagis/ClairMeta#160]
Looking for feedback on this.

Dependencies used by ClairMeta are starting to drop python2 support, so we would not profit from latest development / fix.

Another related issue is that we don't freeze dependencies version when installing from pip, that should probably be done at some point.

**Comment by jamiegau** [comment]
Python3 is pretty standard and universal now.
I see no problems with this myself.  I would recommend.

**Comment by LeoWinterDE** [comment]
I see no problem with dropping python2.

**Comment by kieranjol** [comment]
plz drop py2 support!

**Comment by remia** [comment]
Thanks for the feedback, will keep this in mind for the next release...

**Comment by geor-g** [comment]
Python2 support was dropped some time ago, so I guess this issue should be closed.
