### ISSUE TITLE
ERRORs/WARNINGs connected to CPLs reference xml file only and not the ContentTitleText

### ISSUE THREAD

**Issue by jamiegau** [Ymagis/ClairMeta#161]
Errors/Warning that are connected to specific CPL reference the CPL-XML file and lack reference to the ContentTitleText, or the human readable identifier to the CPL in question.

I would like to request the checks that are connected to CPLs be improved by referencing the ContentTitleText as well as the XML file. The issue may be part of of the overall DCP that is being checked but each CPL may be the responsibility of other entities, and making it easy to identify this would be beneficial.

**Comment by remia** [comment]
Hi @jamiegau,

I think I see what you are getting at but just in case, can you show some sample errors / warning that you think should be improved ? CPLs checks are generally of 2 kinds, either the CPL itself, or the assets referenced from it.

**Comment by jamiegau** [comment]
Lets go over the goal first..
A DCP is a tool used to store multiple CPLs and in many cases these CPLs may reuse the same essences.

If the aim of the tool is to evaluate the status of the DCP, this includes understanding, even though you may have an error in the DCP, it does not mean all CPLs in the DCP have failed or ore non-compliant themselves.  It indicates one of more CPL in the DCP has failed the QC.  For example, as a person making DCP, I may decide to simply recreate the DCP and remove the offending CPL/essences, or replace them.  To do this I need to understand the extent of the issue and what CPLs/essences are effected.

An example of this is a feature DCP with numerous TLR and other CPLs in it.   Just because one of the Trailer CPLs is connected to a error/Failed-QC-indicator, does not mean or indicate other CPLs in the DCP are not available, or OK to be ingested for playback.

As such, the errors need to help the user understand were these lines are.   So if a essence is non-compliant, the error should indicate all CPLs (as ContentTitleText names) referencing the essence.

Ok, taking from some errors in the examples I sent you recently...

`ERROR:check_picture_cpl_encoding
CPL_3f86a82d-1cf6-4941-ba84-6e3d67f7bb5f.xml (Asset jp2k_7709b7a6-f1dc-47f4-ac23-6ef285daf88b_vid.mxf) : Picture must have 5 wavelet transform levels, 0 found`
In this example we have a essence file that failed QC.  I imagine if there were two different CPL file referencing this file, the error would occur twice, one for each CPL file examined..
In this case, updating the above line to say
`CPL_3f86a82d-1cf6-4941-ba84-6e3d67f7bb5f.xml for CPL:ContentTitleText-String (Asset jp2k_7709b7a6-f1dc-47f4-ac23-6ef285daf88b_vid.mxf) : Picture must have 5 wavelet transform levels, 0 found`

`ERROR:check_assets_cpl_metadata
41354b54-530a-4261-a883-cf7454591c66.xml (Asset 3befc196-eb7d-4338-a15e-a8e1e5ebbf48.mxf) : IntrinsicDuration metadata mismatch, CPL claims 552 but MXF 10000`
The referenced CPL FILE means very little to the person reading the error.  It should, for example say
`ERROR:check_assets_cpl_metadata
41354b54-530a-4261-a883-cf7454591c66.xml for CPL:CPL-ContextTitleText  for referenced Asset 3befc196-eb7d-4338-a15e-a8e1e5ebbf48.mxf) : IntrinsicDuration metadata mismatch, CPL claims 552 but MXF 10000`

PKL, um..
`ERROR:check_certif_role
165d11b6-ac01-4b59-a6b0-b6bda44842c5.pkl.xml (Certificate : 1109) : Expecting CS role in CommonName (SM.tdc-uk-user01)
or
ERROR:check_certif_fields_encoding
pkl_1a122f7a-68be-4a78-834b-f1fad438da2f.xml (Certificate : 5) : Subject organizationName field encoding should be PrintableString, got UTF8String`
I will defer to you in regards to PKLs, as they, from my understanding can reference much more, but still, an indication on what CPLs this effects would be beneficial to achieve the goal stated.

Comments or alternate opinions/methods to the madness welcome.

**Comment by remia** [comment]
See #163 for some improvements
