### ISSUE TITLE
SMPTE DCP extended DATA not supported in PROBE result.

### ISSUE THREAD

**Issue by jamiegau** [Ymagis/ClairMeta#166]
Hi Remi,
I was integrating your PROBE data into my online tool and I noticed that CPL extended data from the now standard SMPTE DCP was not yet implemented. 

However Markers are.. and as one came with the other I was surprised.

It's likely quite trivial to implement.  Please place on the TODO list.   It's quite important in my book.

On this, implementation wise, will it be a sub-object (like ['NamingConvention']) from the main?

**Comment by remia** [comment]
Hey @jamiegau,

Are we talking about CompositionMetadataAsset as in https://isdcf.com/papers/ISDCF-Doc6-Composition-Metadata-Guidelines.pdf ? If yes it should already be in the probe, either way I would need to check your DCP CPL to investigate.

**Comment by jamiegau** [comment]
Ok,
Sorry false alarm.
The Probe variables only show up "if" they exist in the CPL metadata.  I specifically pointed PROBE at a DCP/CPL that has  extended metadata and there it was.  It did have me confused as I expected it to showup it it was SMPTE DCP even if not present, just with empty values.  That is not the case...

James

**Comment by jamiegau** [comment]
Yes.
    ```
FullContentTitleText
    ReleaseTerritory 
    VersionNumber 
    Chain 
    Distributor 
    Facility 
    AlternateContentVersionList_Id 
    AlternateContentVersionList_LabelText 
    Luminance 
    MainSoundConfiguration
    MainSoundSampleRate 
    MainPictureStoredArea 
    MainPictureActiveArea
```
To be exact..

OK, I found it..
This data is located in CompositionPlaylist->ReelList->[n]->Metadate.

So lets discuss WHY?

Why are you placing the metadata in reellist?  I only found it as I greped it out..
reellist is data about each reel.  As such, data that is connected to the full CPL, not just a single reel..  Why is it deep down under reellist?
And if multi reels, does it list the metadata multi times in each reel?

I understand this is likely  major change and could break other people's use of the tool.  But it's a little broken from my perspective..
The Metadata branch should be in the root of the cpl cranch of the PROBE data tree for all of the GLOBAL values for the DCP.
Can you get back to me why it was designed this way?
.

**Comment by remia** [comment]
The Probe is for the most part a 1:1 mapping from the DCP XML files. SMPTE CompositionMetadataAsset has been designed itself to be present in the CPL first reel asset list, that's why the probe from ClairMeta is the way it is, there has been no design decision on our part.

> SMPTE 429-16-2014
> A CompositionPlaylist element shall contain exactly zero or one CompositionMetadataAsset element (see Table 2) in the first Reel element of the ReelList element. Other CompositionMetadataAsset elements shall be ignored.

**Comment by jamiegau** [comment]
Um.. Ok I see.
Yes, the Extended MetaData is located in CPL.xml files in the first reel...
So yes, thats how its mapped into the CPL.  So I see your point...

All I can suggest in the end is to somehow mention in the Documentation that Extended MetaData is locationed down there.  As logically thinking..  it does not make sense.
Why look for global data about the CPL in a list about the reels....
Would also suggest in the main object returned by probe that it has something like
obj['ExtendedCplMedaData'] = 'Found under ReelList"

**Comment by remia** [comment]
I'll add a key under the CompositionPlaylist to indicate the presence of metadata (like is done for Picture, Sound, Subtitles, ...). Given that we plan to update the report object, there will already be breaking change anyway for the next version.

**Comment by remia** [comment]
Added in #167
