### ISSUE TITLE
AssetSizeBytes in parse DCP is not set

### ISSUE THREAD

**Issue by jamiegau** [Ymagis/ClairMeta#168]
Hi,
Small bug, See image of prased return structure..
`AssetSizeBytes` is 0...  while size is set correctly..

![image](https://user-images.githubusercontent.com/3303822/96080613-2a10e180-0f03-11eb-96a8-292f112b27ef.png)

**Comment by remia** [comment]
Good catch, looking at it, this is due to the AssetMap Chunk / Length element being optional, so that for some DCPs this field will indeed be 0. Not sure what is the right behaviour here, the global size is already available as a root `size` key and the size per PKL as a `AssetsSizeBytes` key.

**Comment by remia** [comment]
I realised that the `size` key is a human formatted string, not really ideal for processing and include the whole folder size instead of just the DCP assets. We could probably add our own machine integer assets_size key if needed.

**Comment by jamiegau** [comment]
Umm..  This has other issues,,  Maybe it should be called Assetmap_AssetsSizeBytes but also have Files_AssetsSizeBytes being the calculated size on disk, or simply parsing the assetmap and each file it has and counting up the size of each file (it finds).  Not a DCP could have orphaned file in it, which causes a Fail on QC.  Then again should it be a fail or a warning.  I suppose what this variable should be, and I think its good to have, is defined on the way you expected it to be used.

**Comment by remia** [comment]
Added a new ``AssetsOnDiskSizeBytes`` key to the AssetMap probe.

Check #177 if that's something you think will solve your issue here.

**Comment by jamiegau** [comment]
Cool, when will you push it into a release?
Considering this and other size data in Probe.
Under ...['AssetMap']['AssetsSizeBytes'] if 0 we can assume the ASSETMAP file lacks the xml-Tag indicating the size of each file.
If the new ...['AssetMap']['AssetsOnDiskSizeBytes'] is 0, we can assume the assets where not available to the probe process,  for example, only probing XML files and MXF/fonts files not available.

However, I would also like to comment on the base probe_result_json['size'] value.  It gets changed into Human readable text.
This appears inconsistent to me and a json['size'] in bytes and a json['sizeHuman'] should be added to be consistent.

or, as other may be using the json['size'] value already as text human readable..
json['size'] stays as it is and json['sizeBytes'] being the int value, and really should this just be a copy of the value found under ['AssetMap']

Does this base size value represent the size including the xml files? (Probably yes) does it include orphaned files in the directory? (Probably No)

**Comment by remia** [comment]
To answer the above:

* `AssetsSizeBytes` can be anything really, from 0 to the actual assets size or somewhere in between. The DCP in our test set only have the length tag for the essences and not the (XML) structure files.
* `AssetsOnDiskSizeBytes` should be non-zero as the structure files should be there, but as you mention the DCP could be incomplete (Version File).
* The root `size` key is the size of the whole folder (every single files, it doesn't care), for backward compatibility reasons I didn't changed it's name but added a `size_bytes` key next to it. See #177

**Comment by remia** [comment]
Closing this one, will be part of the next release.
