### ISSUE TITLE
CPL/ReelList/Assets/Markers/MarkerList inconsistent

### ISSUE THREAD

**Issue by jamiegau** [Ymagis/ClairMeta#175]
Looking at the Probe output,
For example, on a TEST DCP I made.. I am getting the following..
![image](https://user-images.githubusercontent.com/3303822/108615334-11877980-7457-11eb-9547-f80754208d30.png)

The structure of the MarkerList is different between reel1 and reel2.
I made the Test DCP with the test version of DCP-O-Matic if you would like to reproduce this issue.

**Comment by remia** [comment]
Hey @jamiegau,

Thanks for the report.

Could you send me the DCP (*.xml files mostly) ?

**Comment by jamiegau** [comment]
Sent..

**Comment by remia** [comment]
Thanks @jamiegau, that's a good catch.

I fixed it in #176 if you want to give it a try.

**Comment by jamiegau** [comment]
I'm sure it's good Remia, you are a far better coder then I am.  I codec my use of it to look for either method.  So I'm good.   But it is good to catch these small bugs under specific conditions.  Markers are becoming more important, so cool we can deal with them.

In the next release to main, I am sure if a bug shows its head, in my tool, "I'll be back" (Imagine Arnold Schwarzenegger)
