### ISSUE TITLE
Picture wavelet transform levels SMPTE compliance, Error as found 0 (Picture must have 5 wavelet transform levels)

### ISSUE THREAD

**Issue by jamiegau** [Ymagis/ClairMeta#180]
Question,
This error,  Can you have 0?
And if you find 0, should this be a warning or an error?

**Comment by remia** [comment]
That error rings a bell.

I think this may indeed be lowered to warning as it probably indicate as-dcplib didn't found the information while probing the MXF. I need to check again if that kind of JP2K descriptor is mandatory or not.

**Comment by jamiegau** [comment]
That was my initial thought.  If 0, there must be an issue in reading the actual value.  Leading to a false positive.

**Comment by remia** [comment]
@jamiegau could you send me one of those files so that I can confirm this ? If this happen for both IOP and SMPTE, one of each would be useful. Encrypted is fine.

**Comment by remia** [comment]
Please continue discussion in #198  if needed, thanks.
