### ISSUE TITLE
Empty element text content check in Assetmap

### ISSUE THREAD

**Issue by matmat** [Ymagis/ClairMeta#183]
https://github.com/Ymagis/ClairMeta/blob/376a5e2e6f71637d984a501a0fe01ec0ec2aba43/clairmeta/dcp_check_am.py#L61-L66

Why do we check for empty element text content here?

I think it should be allowed with empty element text content. The only constraint I can find is that some of these elements must be present, but there is no constraints on their text contents.

`Issuer` and `Creator` elements are mandatory both for Interop and SMPTE.  `AnnotationText` (top level) element are optional. This is already checked for with the XML schemas.

Both standard documents contains the following text:

> _The `AnnotationText` element is a free-form, human-readable annotation (...) it is meant strictly as a display hint to the user._

References
- mpeg_ii_am_spec.doc (v3.4) 4.1.2, 4.1.5, 4.1.6
- SMPTE ST 429-9:2014 5.2, 5.3, 5.6

**Comment by remia** [comment]
Agreed that this check is not backed by standard and it is indeed listed as warning in the default check profile.

If memory serve, it was added to match another commercial check tool, maybe EasyDCP. It maybe good to check that if someone has access to that tool, if so we should add a description here.

If we don't find reason we could delete it entirely of lower it's error level further more to info or silent ?

**Comment by matmat** [comment]
I think lowering to INFO would be a good solution.
