### ISSUE TITLE
Validation fails when system reports .xml mime-type as application/xml

### ISSUE THREAD

**Issue by mivk** [Ymagis/ClairMeta#20]
On Ubuntu 16.04, the mime-type reported for .xml files is "application/xml". So all DCPs fail validation because dcp_check_utils.py only accepts "text/xml". I guess Mac OS X reports a mime-type of "text/xml"?

The problem can be corrected by accepting both mime-types:

```
$ diff -u /usr/lib/python3.5/dist-packages/clairmeta/dcp_check_utils.py.orig /usr/lib/python3.5/dist-packages/clairmeta/dcp_check_utils.py
--- /usr/lib/python3.5/dist-packages/clairmeta/dcp_check_utils.py.orig	2018-03-19 17:59:01.000000000 +0100
+++ /usr/lib/python3.5/dist-packages/clairmeta/dcp_check_utils.py	2018-03-28 21:11:02.000000000 +0200
@@ -22,7 +22,7 @@
 def check_xml(xml_path, xml_ns, schema_type, schema_dcp):
     # Correct file type (magic number)
     xml_magic = magic.from_file(xml_path, mime=True)
-    if xml_magic != "text/xml":
+    if xml_magic != "text/xml" and xml_magic != "application/xml":
         raise CheckException(
             "File type unknown, expected XML Document but got {}".format(
                 xml_magic))

```
But maybe the mime-type should not be checked at all, only the content? What mime-type would be reported on various Windows versions? It seems a fragile check, and actually irrelevant. DCP players only care about the content, as far as I know.

**Comment by remia** [comment]
Thanks for this report, these issue is introduced by commit bdc3d2c1c3d3679fd2ec9f77c43e4162e1d66758.

I tend to agree with you, the libmagic based checks are not really robust (depends on both the platform and local mime type database file as far as I know; also found some case where the libmagic detection rules produced some strange results). I did a PR #23 for this.
