### ISSUE TITLE
Error parsing XML "out of memory: line 1, column 0" after updating libexpat

### ISSUE THREAD

**Issue by jamiegau** [Ymagis/ClairMeta#212]
MAJOR issue has popped up.  URGENT fix required.  I am not sure how to regress to a working version as its system library related.

After doing a rebuild of my dockers APLINE containers  or updating my ubuntu 20.04 LTS servers..  clairmeta starts to fail to work with the following error example.

```
python3 -m clairmeta.cli check -type dcp  Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV
2022-02-24 21:57:49,089 - Clairmeta - INFO - Probing DCP : Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV
2022-02-24 21:57:49,090 - Clairmeta - ERROR - Error parsing XML Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV/ASSETMAP : out of memory: line 1, column 0
2022-02-24 21:57:49,090 - Clairmeta - ERROR - Error parsing XML Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV/VOLINDEX : out of memory: line 1, column 0
2022-02-24 21:57:49,090 - Clairmeta - ERROR - Error parsing XML Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV/CPL_Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV.xml : out of memory: line 1, column 0
2022-02-24 21:57:49,091 - Clairmeta - ERROR - Error parsing XML Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV/PKL_52a2e88d-bffb-4b6f-93bc-bf4fe5ee3ae6.xml : out of memory: line 1, column 0
2022-02-24 21:57:49,091 - Clairmeta - ERROR - Error parsing XML Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV/CPL_Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV.xml : out of memory: line 1, column 0
2022-02-24 21:57:49,091 - Clairmeta - ERROR - Error parsing XML Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV/PKL_52a2e88d-bffb-4b6f-93bc-bf4fe5ee3ae6.xml : out of memory: line 1, column 0
2022-02-24 21:57:49,091 - Clairmeta - ERROR - Error parsing XML Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV/CPL_Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV.xml : out of memory: line 1, column 0
2022-02-24 21:57:49,092 - Clairmeta - ERROR - Error parsing XML Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV/PKL_52a2e88d-bffb-4b6f-93bc-bf4fe5ee3ae6.xml : out of memory: line 1, column 0
2022-02-24 21:57:49,092 - Clairmeta - INFO - Total time : 0.00 seconds
2022-02-24 21:57:49,340 - Clairmeta - INFO - Checking DCP : Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV
2022-02-24 21:57:49,346 - Clairmeta - INFO - Check report:

Status : Fail
Path : Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV
Size : 1.87 GiB
Total check : 5
Total time : 0.00 sec

Warning(s):
  + Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV
    . Foreign files detection (not listed in AssetMap).
      CPL_Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV.xml
      PKL_52a2e88d-bffb-4b6f-93bc-bf4fe5ee3ae6.xml
      Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV_01.mxf
      Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV_audio_01.mxf
Error(s):
  + Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV
    . Only one AssetMap and VolIndex shall be present.
      Missing VolIndex file
      Missing Assetmap file

DCP - Parasite_TLR-2_S_KO-EN-OCAP_20_2K_CJ_20190624_CJP_IOP_OV - Check failed
```

And I am unsure how to regress to a working version.  I imagine  system library that clairmeta uses is not compatible.
As I cannot regress, this is urgent.

I know its a update issue, as I had a Ubuntu 20.04 system that DID work..   and I was looking at what pip libs it used to see if that may have been an issue..  But it was only after I did a "apt full-upgrade" did the same issue start occuring on the server that did once work.  So I assume, there is an updated lib that clairmeta relys on that has broken the xml parsing.

**Comment by remia** [comment]
Hi @jamiegau,

Would you be able to share the DCP (.xml files only) and a simple Docker image where to reproduce the error?

**Comment by jamiegau** [comment]
Ok, did the digging, it appears expat library had a major security issue and has been updated.  But this updated version is broken.  to go back to release version under ubuntu 20.04 LTS
`apt-get install libexpat1=2.2.9-1build1 libexpat1-dev=2.2.9-1build1`

For alpine linux, it appears to be very difficult as they REPLACED the release apk in the repo with the broken version.  They didn't give it a new version number.  CRAZY.  So no way to regress to a working path under ALPINE.  looking into.

**Comment by jamiegau** [comment]
This issue has been identified on the expat issue tracker under
https://github.com/libexpat/libexpat/issues/572
go there to read the gritty detail of the bug.

**Comment by hartwork** [comment]
Hi @remia I see that ClairMeta is using xmltodict for XML Parsing. xmltodict uses a colon (`':'`) for a namespace separator, which is incompatible with Expat >=2.4.5 security fixes. I have filed an issue with xmltodict at https://github.com/martinblech/xmltodict/issues/289 about just that. If you would like to fix this issue in ClairMeta independent of xmltodict, you could e.g. extend the call at…
https://github.com/Ymagis/ClairMeta/blob/eb60081485741ada5e4b5da022e44e7aef8b139c/clairmeta/utils/xml.py#L202-L210
…to pass a different namespace separator, e.g. `namespace_separator='\n'`. A space (`' '`) would also do. I cannot guarantee that's the whole fix without testing more, but that would be the direction. Does that make sense?

**Comment by remia** [comment]
Hi @hartwork !

Really appreciate you taking the time to look into that, thanks. The fix you suggest seems straightforward to me and could be implemented pretty fast indeed. I'm not sure on the status of `xmltodict` to it would be best if we can fix it from there, @jamiegau would you be able to check if that fix the issue?

**Comment by hartwork** [comment]
@remia another place where the separator seems to hardcoded (that would need in-sync adjust (and maybe a new constant for re-use) as it https://github.com/Ymagis/ClairMeta/blob/eb60081485741ada5e4b5da022e44e7aef8b139c/clairmeta/utils/xml.py#L80

**Comment by remia** [comment]
Good catch @hartwork, indeed I noticed the same thing when unit test started to fail.

Opened a PR #213 hopefully @jamiegau can validate if it's working.

**Comment by bioleyl** [comment]
Hi,

Got the same problem and after downgrading libexpat1 I could check DCP again but I think there is something else.

I got two machines with clairmeta. One was updated and the other not. The not update one still has no problems but the other one even after downgrading libexpat still faces some problems. I got a DCP which can't be probe on that machine but the probe works on the not updated one.

**Comment by bioleyl** [comment]
I got no error but empty informations  

```
python3 -m clairmeta.cli probe -type dcp CARLOTTA_MelleOgin1962_FTR-3_S_JA-XX_JP_10_4K_SCK_20210923_TIT_IOP_OV_2109TIT1524
{'asset_list': {},
 'assetmap_list': [],
 'count_file': 0,
 'cpl_list': [],
 'kdm_list': [],
 'package_type': 'OV',
 'path': 'CARLOTTA_MelleOgin1962_FTR-3_S_JA-XX_JP_10_4K_SCK_20210923_TIT_IOP_OV_2109TIT1524',
 'pkl_list': [],
 'schema': 'Unknown',
 'size': '146.06 GiB',
 'size_bytes': 156831267720,
 'type': 'DCP',
 'volindex_list': []}
```

**Comment by remia** [comment]
Hi @bioleyl, which version of ClairMeta are you testing on? Does it include the fix from the PR?

**Comment by bioleyl** [comment]
I tried all the versions (1.1.1, 1.1.2, 1.2.0 and the PR). None are working.

**Comment by remia** [comment]
I assume your downgrading broke something else then? I'll push a new version to fix the issue so maybe you can try getting back to the latest expat.

**Comment by bioleyl** [comment]
You are releasing a new pip package?

**Comment by remia** [comment]
Yes, version 1.2.1 should be available from PyPI now.

**Comment by hartwork** [comment]
@remia awesome! :+1:
