### ISSUE TITLE
from tests import DCP_MAP ModuleNotFoundError: No module named 'tests'

### ISSUE THREAD

**Issue by herrschmidt** [Ymagis/ClairMeta#217]
Hi,
I am trying to run the unit tests in Python 3.6 on a Windows 11 computer, but keep on getting the error:

`from tests import DCP_MAP
ModuleNotFoundError: No module named 'tests'`

I cloned the test materials into C:\Users\MyUserName\tests\resources after installing clairmeta to python3.6 with pip and downloaded the test scripts. I tried running them from the downloads folder and also copied them into the site-packages/clairmeta folder and tried it from there.

How can I resolve this?

**Comment by herrschmidt** [comment]
Okay, now it works:so I had to put the python test files into the root directory of the clairmeta install dir and also copy the resources folder into the same install dir (python3.6/Lib/site-packages/clairmeta). Now it works.

**Comment by remia** [comment]
Thanks for the update @herrschmidt, please let us know if we need to update the instructions in https://github.com/Ymagis/ClairMeta#contributing
