### ISSUE TITLE
Add parsing of DCP folder name to metadata

### ISSUE THREAD

**Issue by robin-francois** [Ymagis/ClairMeta#232]
In some circumstances, the information in the DCP folder name can have importance and since ClairMeta already has all the functions to parse the folder name, it could be useful to add it to the metadata output.

I have prototyped an implementation, but it obviously requires to be reviewed: https://github.com/robin-francois/ClairMeta/commit/0d16dacaa4c2825a741c1fb74512d115f6a37077

**Comment by remia** [comment]
Thanks @robin-francois, would you mind opening a PR for that one so that we can review?

**Comment by robin-francois** [comment]
Opened #233 !
