### ISSUE TITLE
DCP Naming Convention checks

### ISSUE THREAD

**Issue by bquandt** [Ymagis/ClairMeta#235]
I think its wrong, potentially misleading,  to use the word 'warning' in DCP naming convention checks.

While I think it would be great for the ISDCF recommendations to have been made required within the XML's itself, that is not what happened.   Usage of the English word 'warning' is too closely tied to being in error or being wrong.   

I suggest a better classification of such checks, e.g. maybe 'recommendation' vrs 'warning' would be better? 

I think the word 'warning' creates confusion for a person thinking a DCP is 'bad' (aka a false positive/negative) when it really is not.   

It would be nice to change language to be  in alignment with what ISDCF/SMPTE seemed to do, use the word 'recommendation.'

**Comment by remia** [comment]
Sorry for the silence @bquandt, I agree with your point. Maybe we should turn the DCNC related warnings into info, which is a level of errors below warning in ClairMeta default [reporting](https://github.com/Ymagis/ClairMeta/blob/develop/clairmeta/profile.py#L17).

**Comment by kieranjol** [comment]
Yeah, in the hundreds of dcps that were qc’d in an archive I worked for, I think maybe one ever followed the convention perfectly. And he worked in the archive :)

**Comment by worldpoop** [comment]
"Alert"?  "Advisory"?  There may be a place for "Warning" sometimes, but
most seem just to be advisories rather than notices of real potential
problems.  It's a bit of a mouthful, but "Advisory" is pretty accurate.
