### ISSUE TITLE
Move "Certificate signature check failure : certificate has expired" error to a warning or ignore

### ISSUE THREAD

**Issue by jamiegau** [Ymagis/ClairMeta#243]
Move "Certificate signature check failure : certificate has expired" error to a warning or ignore, as DCI has updated specs to this effect.

**Comment by jamiegau** [comment]
Notes:

```
DCI Releases DCI Specification, DCSS Version 1.4.4
Approved for Distribution January 3, 2024

DCSS VERSION 1.4.4

DCSS Changelog since 1.4.3

-  Permit playback of CPLs after the signing certificate has expired
-  Relax ingest and storage capacity requirements


The DCSS 1.4.4 is available as an online HTML edition and as a PDF file. The PDF version contains pagination and includes page numbers whereas the HTML version does not.
The PDF version is considered the definitive instance of the Digital Cinema System Specification, Version 1.4.4.

There is also a redline version that compares DCSS 1.4.4 to DCSS 1.4.3, showing additions and deletions. The redline is available in an online HTML edition.
Future DCSS revisions will modify the DCSS Version 1.4.4.

DOCUMENT LINKS

HTML edition of the DCSS, Version 1.4.4  is:
https://documents.dcimovies.com/DCSS/42cfeb997ae72dd484f7b027547e6e0bfad43ecf/

PDF file of the DCSS, Version 1.4.4, is:
https://documents.dcimovies.com/DCSS/42cfeb997ae72dd484f7b027547e6e0bfad43ecf/Digital%20Cinema%20System%20Specification.pdf

HTML redline of DCSS 1.4.4 and DCSS 1.4.3 is:
https://documents.dcimovies.com/DCSS/42cfeb997ae72dd484f7b027547e6e0bfad43ecf/index-diff.html

See the DCI Specification, DCSS page for information and addenda links:
https://www.dcimovies.com/specification/index.html



Thank you,

Digital Cinema Initiatives, LLC (DCI)
```

**Comment by remia** [comment]
Thanks for the notice @jamiegau, I assume this is not going to cause ingest / playback issues on existing hardware if you are suggesting we move this to warning or less?

**Comment by jamiegau** [comment]
This issue did result in the biggest dark screen event of DCI.   On new years day, hundreds of cinemas had to close for a few days as this issue showed itself.

From my understanding, and I am waiting for the ISDCF meeting note on it, I was unable to attend. This is based on a lack of clarity in the DCI specification on if a singer certificate is out of date, causing a show to fail to load.  Technically, a signer cert should not be considered, but in general security considerations, it should.

The ambiguity resulted in different vendors taking different paths.

It was not indicated what DCI expected until the above update.

Up-to-date systems appear to have fixed this issue and had no issues, but older units, Sony being the main vendor, refused to play.
Others too had issues especially if not on the latest firmware.

So to answer your question.  Yes, some players do not work, but they are weeded out quickly as the worldwide issue has forced this point.  And you have to have addressed it if your an operating cinema and had the problem.
I would move it into WARNING.  Was considering ignoring it, but we should get indications when producers overlook doing stuff like updating a signer certificate.

**Comment by remia** [comment]
Thanks for the details, yeah I remembered that event, hence me checking!

Will make it a Warning then with an updated note, unless there are any objection.

**Comment by geor-g** [comment]
> This issue did result in the biggest dark screen event of DCI. On new years day, hundreds of cinemas had to close for a few days as this issue showed itself.

@jamiegau Was this covered in media?

**Comment by jamiegau** [comment]
If you look at this
https://www.isdcf.com/certs-expiring/ 
That goes into deep detail on the event/issue..,
It lists the type of units affected.  I would guesstimate there are 10,000s of units in this position.
Drafthouse, due to its reliance on Sony at some locations.. had to close them completely for a few days before they sent out new VF-CPLs that had the current date signed-certs of the CPLs.
https://www.theverge.com/2024/1/1/24021915/alamo-drafthouse-outage-sony-projector

Many cinemas probably had a mixture of players and would have limped along with non affected projectors.

I would consider it easily the biggest dark screen event in DCI history.
However, I don't expect you would hear that from any official sources.
However, we are free to speculate here   :)

**Comment by geor-g** [comment]
@jamiegau -- I knew the first link, but the second one was new to me, thanks!
