### ISSUE TITLE
Missing dependecy

### ISSUE THREAD

**Issue by KoMaSH** [Ymagis/ClairMeta#244]
Hello everybody,
I am new to the whole thing of Linux/Ubuntu. And I am having issues to instal some dependencies for clairmeta.
In case is the 
asdcp-info
and
asdcp-unwrap
I have tried with CMake and that was a fail on the github page for asdcp I cant find anything to make sense to my brain so I am turning to you guys for help.
- Clairmeta - WARNING - Missing dependency : asdcp-info
- Clairmeta - WARNING - Missing dependency : asdcp-unwrap
Any help is welcome.
Thank you

Using Ubuntu 22

**Comment by remia** [comment]
Hi @KoMaSH,

You could have a look at how our Github Action do it [here](https://github.com/Ymagis/ClairMeta/blob/develop/.github/scripts/linux/apt/install_test_env.sh).

Hopefully that should get you on the right track.

**Comment by remia** [comment]
Looks like we missed this in the Readme, sorry, will make sure to add it! Here is the command line:
`python3 -m clairmeta.cli check -type dcp path/to/dcp_vf -ov path/to/dcp_ov`

For copy paste from / to a Linux terminal, you can try Ctrl-Shift-C / Ctrl-Shift-V maybe!

**Comment by KoMaSH** [comment]
Thank you very much remia.
