### ISSUE TITLE
Corrupt file, expected hash B/cUI+/nFxoma8z841hcMsXJ2Hc= but got H9srbkwDakdQl4FWJ25Hh91RbjQ=

### ISSUE THREAD

**Issue by JeromeLesaint** [Ymagis/ClairMeta#247]
Hi,

I have verified several DCPs created by a soft. Sometimes, i have a hash error by reverify DCP with clairmeta.

Have you any idea about that ?

Other thing, in clairmeta, you have several settings that call to digicine.com for retrieving XSD files.
However, this site doesn't exist at this time, it's replaced by another site call cinepedia.

Thanks

**Comment by jamiegau** [comment]
If you have a hash error, you have a problem.
I verify 20 DCPs per day using it, and it is always right.  If I get a hash error, the file is no longer right.
So if you're getting them, it likely means something is going wrong.  You can also try DCP-O-Matic for a second opinion.
Could it be a problem based on how you're sharing the files over a network.   Or many other reasons why it's not reading right.

The XSD files are embedded into the package.
XSD files are not expected to actually live on the internet at the URLs given.  Its more just a name space thing.
I am not sure why they did it this way.  Ask an LLM.

**Comment by JeromeLesaint** [comment]
Thanks a lot James. Indeed, i think there is a problem with the internal process of my client. I have verified all of hash in PKL file of a DCP and one of three hash is on error. I will check more details with my client. Have a nice day.
