### ISSUE TITLE
check_subtitle_cpl_uuid wrong for SMPTE subtitles

### ISSUE THREAD

**Issue by matmat** [Ymagis/ClairMeta#30]
For SMPTE subtitles the uuid in the CPL refers to the mxf container, not to the uuid in the wrapped subtitle xml. This check fails for unencrypted SMPTE subtitles because it compares the MainSubtitle Id element in the CPL against the XML. This is correct for Interop (which is not mxf-wrapped) but not for SMPTE.

Please instead check against the subtitle mxf container uuid.

**Comment by remia** [comment]
Thanks for noticing this.

I just re-checked the SMPTE standard (ST 428-7) and find it not clear : 
> The Id element shall uniquely identify the reel for asset management purposes. It shall be encoded in the element body as a urn:uuid [RFC 4122].

In our test dataset (to be published once we find a host), we have un-encrypted SMPTE DCP with subtitles (generated by Clipster) and here the CPL MainSubtitle/Id = MXF AssetUUID = Subtitle XML Id. I don't know if this is just vendor specific but if not I don't really understand what is the purpose of the Subtitle XML Id element ? It reference nothing, just is a unique Id ?

Beside, I noticed that this check is not currently done for Interop DCP as it should, maybe this was a typo and should only be done for Interop and not SMPTE. So the fix would be pretty simple.

**Comment by matmat** [comment]
Interesting! You are right it is not clear at all!

I have a lot of samples where CPL MainSubtitleId != MXF AssetUUID. They have all played without problems on IMS2000/Cat862/Cat745.

I can check which tool created them if that would help?

**Comment by remia** [comment]
Thanks, yes this could help.

I will try to find some too and report back.

**Comment by matmat** [comment]
Actually I have this sample, which is a current DCP authored by Eclair :-)

The AssetID (xml uuid) does not match the AssetUUID (mxf uuid)

CPL:
```
<CompositionPlaylist `xmlns="http://www.smpte-ra.org/schemas/429-7/2006/CPL">
   <Id>urn:uuid:71dec272-0968-4e61-b697-0d4e57207361</Id>
```
...
```
  <Issuer>eclair</Issuer>
  <Creator>ClipsterDCI 6.6.0.0</Creator>
```
...
```
        <MainSubtitle>
          <Id>urn:uuid:61d426c9-e971-40fd-b97a-57e97312b89e</Id>
```

```
$ asdcp-info -d -i 61d426c9-e971-40fd-b97a-57e97312b89e.mxf
SMPTE 429 file essence type is Timed Text, (29375 edit units).
       ProductUUID: 43059a1d-0432-4101-b83f-736815acf31d
    ProductVersion: Unreleased 1.12.51
       CompanyName: DCI
       ProductName: asdcplib
  EncryptedEssence: No
         AssetUUID: 61d426c9-e971-40fd-b97a-57e97312b89e
    Label Set Type: SMPTE
         EditRate: 25/1
ContainerDuration: 29375
          AssetID: f3c4b992-a508-4099-85a4-a304e8fbf8c0
    NamespaceName: http://www.smpte-ra.org/schemas/428-7/2010/DCST
    ResourceCount: 1
    9019a5f8-6bbf-4d43-ae27-8afe4121a705: application/x-font-opentype
```

**Comment by remia** [comment]
Thanks for this detailed analysis !

I think, in the case of SMPTE subtitles we should do the following :
*  Check that CPL MainSubtitle/Id = MXF AssetUUID
*  (For un-encrypted) Check that MXF AssetID or TimedTextDescriptor/ResourceID = XML Id
For Interop :
*  Check CPL MainSubtitle/Id = DCSubtitle/SubtitleId = Folder Id (maybe not mandatory)

I'm not sure in which standard is specified the AssetID MXF tag, for now I only found that indeed the ResourceId should match the Xml Id, as seen in the figure p.8 of ST 429-5. I'll try to find where the AssetID comes from...

**Comment by remia** [comment]
I opened a new Pull Request that should fix this.

**Comment by matmat** [comment]
To complicate this further Dolby/Doremi DCP-2000 versions below v2.8.18 **_requires_** that the MXF Asset uuid and XML uuid be different. From the v2.8.18 release notes[1]:

> • Fixed an error where the server did not extract SMPTE timedtext (as in subtitles/captions) from
> the MXF file that was incorrectly created using the same universally unique identifier (UUID) for
> the MXF file and the main XML inside the MXF files. [DCPLYR‑3418]

[1] http://doremi-techno-legacy-portal.dolbycustomer.com/images/Portal/Cinema_Players/DCP2000-DCP2K4/pkg/SW_2_6_4/Dolby_DCP_ShowVault_Software_Release_Notes_005282_Issue_6.pdf

**Comment by remia** [comment]
Opened a PR. for this.

I close this issue, discussion here #41.

**Comment by matmat** [comment]
Sorry for commenting on this old issue, but for completeness, note that [RDD 52](https://ieeexplore-ieee-org.proxy.lib.ltu.se/document/9161348) clarifies this somewhat:

> ### 10.4 Timed Text Track Files
> #### 10.4.1 Asset UUID
> The MXF `AssetUUID` shall be identified by a unique `urn:uuid` of Type 4 value IETF RFC 4122
> #### 10.4.2 Resource ID
> The MXF `ResourceID` shall be equal to the `Id` element `urn:uuid` of Type 4 value IETF RFC 4122 of the contained DCDM XML essence.

**Comment by remia** [comment]
Thanks for the note, if I understand correctly we cover this already, so I added the RDD in the reference section of the check docstring: https://github.com/Ymagis/ClairMeta/pull/179/files#diff-c02c9bc9ea12e78501ebd1ba471d199c911ffdb74775dd4f5cd73edacc6e42faR563

**Comment by matmat** [comment]
This is also described in some more detail in [edcf-rp_acroynms_and_terms_20180620_v001.docx.pdf](https://drive.google.com/file/d/1NFGieUMSfa5Q6aCfKisxje9OxRXYeTt_) available from https://www.smptedcp.com/resources/technical-documents
