### ISSUE TITLE
check_cpl_reel_duration_picture_subtitles should be enforced only for Interop

### ISSUE THREAD

**Issue by matmat** [Ymagis/ClairMeta#34]
For Interop:
MainSubtitle Duration **must** be equal to MainPicture Duration.

For SMPTE:
MainSubtitle duration is allowed to be **less than or equal** to MainPicture Duration. See references below

- ST 429-2:2013 section 9.4:
_The Duration element shall be present within every Asset element that refers to an external track file. The value of all Duration elements in a reel, **_with the exception of timed text elements_**, shall be equal. The Duration of the Reel shall be determined by the MainPicture element, per the provisions of [SMPTE ST 429-7], or the MainStereoscopicPicture element, whichever is present._

- ST 429-2:2013 section 9.6:
_Each Reel element in a Composition Playlist document shall contain one (1) MainPicture element [SMPTE ST 429-7] or one (1) MainStereoscopicPicture element [SMPTE ST 429-10]. This element shall refer to a Picture Track File as defined by [SMPTE ST 429-3]. If the element name is MainStereoscopicPicture, the referenced Track File shall also conform to [SMPTE ST 429-10]._

- ST 429-7:2006 section 5:
_At the start of a given Reel, playback of all Assets contained within the Reel shall start simultaneously at the Entry Point given for each respective Track File. **The duration of a Reel shall be equal to the duration of the Reel’s MainPicture Asset**, or the Asset with the shortest duration if the MainPicture Asset is not present._
(Figure 3 clearly shows a MainSubtitle Asset with shorter Duration than the two other assets)

- mpeg_ii_pack_constraints_2v5.doc section 7.5:
_All subtitle tracks referenced by a given Composition Playlist must share identical language.The subtitle file shall not contain any subtitles outside the playable portion determined by the EntryPoint and Duration of the subtitle asset._

- mpeg_ii_pack_constraints_2v5.doc section 7.8:
_**All Assets** referenced by a single Reel shall have the same Duration_

**Comment by remia** [comment]
Very good overview thanks !

I'll update the check when I get the time (most likely not in the next 2 weeks), feels free to open a pull request if you are in a hurry. This check was tagged as a warning but could be an error with the update.

**Comment by remia** [comment]
@matmat I opened a PR. that implement this, #42
