### ISSUE TITLE
libmagic missing

### ISSUE THREAD

**Issue by LeoWinterDE** [Ymagis/ClairMeta#5]
On Mac, after installing:
```
easy_install pip
pip install clairmeta
```
The libmagic library is missing, `easy_install libmagic` or `pip install libmagic` doesn't help.

**Comment by remia** [comment]
Good catch.

We use python-magic (https://github.com/ahupp/python-magic), on mac you should install libmagic : `brew install libmagic`. Does that help ?

**Comment by LeoWinterDE** [comment]
Yes, thanks that works.

**Comment by remia** [comment]
Ok, I'll try to update the Readme to provide macOS specific install instructions.
