### ISSUE TITLE
Ubuntu bionic packaging

### ISSUE THREAD

**Issue by remia** [Ymagis/ClairMeta#50]
Uploading the generated .deb don't work for bionic, travis report :

`Unable to upload files: Could not extract metadata for artifact "pool/main/bionic/asdcplib/asdcplib_2.10.31_amd64.deb" content might be 'malformed.`

**Comment by remia** [comment]
Might be related :
*  https://github.com/travis-ci/travis-ci/issues/9656
*  https://unix.stackexchange.com/questions/441032/deb-package-cannot-upload-to-bintray-when-package-is-build-using-ubuntu-18-04

**Comment by rzr** [comment]
Crosslinked issue:

* https://github.com/travis-ci/travis-ci/issues/9656
* https://github.com/Ymagis/ClairMeta/issues/50
* https://twitter.com/RzrFreeFr/status/1090633522816143362

**Comment by remia** [comment]
Thanks @rzr !

Are you aware of any development on @jfrog side ? Is it on their list ?

**Comment by rzr** [comment]
> Thanks @rzr !
> 
> Are you aware of any development on @jfrog side ? Is it on their list ?

Not really, feel free to RT this:

https://twitter.com/RzrFreeFr/status/1090633522816143362

If no feedback I'll try to email some contact.

**Comment by remia** [comment]
Great news, thanks for the headup @rzr  !

**Comment by remia** [comment]
I released a new version and it seems like the bionic build sucessfully uploaded to bintray.

**Comment by remia** [comment]
Confirming that the package successfully install on bionic, closing this issue.
