### ISSUE TITLE
How to select json or XML via python libary?

### ISSUE THREAD

**Issue by kieranjol** [Ymagis/ClairMeta#51]
I am incorporating clairmeta into a python script by using your instructions:
```
dcp = DCP(absolute_dcp_path)
        # Parse DCP
        dcp.parse()
        # Check DCP
        dcp.check(hash_callback=console_progress_bar)
```
I would like to know what arguments I could use to get the JSON or XML outputs?

Thanks,

Kieran O'Leary
Irish Film Institute.

**Comment by remia** [comment]
Assuming you are after the parsing metadata.

Maybe the Readme is not that clear, the `DCP.parse()` returns a python dictionary containg all the metadata, then it is left to the user to convert to appropriate formats.

Here is some basic DCP parsing and formating in XML and JSON formats, code is adapted from https://github.com/Ymagis/ClairMeta/blob/develop/clairmeta/cli.py#L53 which is the code for the command line interface of Clairmeta (_warning, I didn't test it_) :

```
import json
import dicttoxml
from clairmeta.utils.xml import prettyprint_xml
from clairmeta import DCP

dcp = DCP(absolute_dcp_path)
dcp_dict = dcp.parse()
json_str = json.dumps(dcp_dict , sort_keys=True, indent=2, separators=(',', ': '))
xml_str = dicttoxml.dicttoxml(dcp_dict , custom_root='ClairmetaProbe', ids=False, attr_type=False)
xml_pretty = prettyprint_xml(xml_str)
```

Hope that help.

**Comment by kieranjol** [comment]
I can't test right now but that makes perfect sense. Thanks!

**Comment by kieranjol** [comment]
Many thanks for your help, i've just integrated clairmeta into our workflows via: https://github.com/kieranjol/IFIscripts/commit/39c24ed322098ba591234c6825d48cc3046cf69a
I'd mentioned considering this at a talk during the FIAF 2018 congress, and I only got around to it now :) Thanks for the amazing tool!

**Comment by remia** [comment]
Glad to help :)

Cheers,
