### ISSUE TITLE
Error is given in SMPTE subtitles without <Language> tag, though <Language> is optional

### ISSUE THREAD

**Issue by cth103** [Ymagis/ClairMeta#73]
The XSD for SMPTE subs says

<xs:element name="Language" type="xs:language" minOccurs="0" default="en"/>

so I don't think ClairMeta should give an error if no <Language> tag is present in some SMPTE subtitle XML.

Thanks!

**Comment by remia** [comment]
You are right, I will add an early exit in the `check_subtitle_cpl_language` method to cover this. Do you have an exemple for this other than the DCP linked in the other ticket ? Just checking as in this case it throws an error for another reason (language is specified as 'Unknown').

I will add that this is only valid for SMPTE DCP, Interop require the Language tag to be present.

**Comment by cth103** [comment]
Thanks.  I tested your patch and it looks good to me.  Here's a DCP which should help with testing:
https://dcpomatic.com/Clairmeta_FTR-1_F_MOS_2K_20190108_SMPTE_OV.zip

**Comment by remia** [comment]
Indeed, this seems to fix the issue, thanks for the test content !

**Comment by matmat** [comment]
Please note that the ``Language`` element is mandatory if more than one off-screen text track is present:

From ST 429-2:2013 (D-Cinema Packaging – DCP Operational Constraints):

> **9.8 Timed Text Tracks**
(...)
> When more than one off-screen text track asset of the same type (``ClosedSubtitle`` or ``ClosedCaption``) is present, the ``Language`` attribute shall be used. The ``Language`` attribute value of each off-screen text track shall be unique among the set of similarly-typed off-screen text tracks. The value of the ``Language`` attribute shall be used to identify material of the same off-screen text track from Reel to Reel for each ``Asset`` type instance.

**Comment by cth103** [comment]
Thanks @matmat, I will take that into account in DCP-o-matic.
