### ISSUE TITLE
LoadFont element is mandatory for SMPTE subtitles

### ISSUE THREAD

**Issue by matmat** [Ymagis/ClairMeta#83]
Even though the XML schema specified in the two later versions of ST428-7 makes the LoadFont element optional by specifying:

> ```<xs:element name="LoadFont" minOccurs="0" maxOccurs="unbounded">```

This is further constrained by ST 429-2:2013:

> **8.4.1 Fonts for Timed Text**
> When Text elements are present in the Timed Text essence, one (1) LoadFont element shall be present. Timed Text essence shall not contain more than one (1) LoadFont element.

And also mentioned (more loosely) in ST 428-7:2014:

> **5.11 LoadFont Element [instance optional]**
> (...)
> When one or more `Text` elements are present, at least one `LoadFont` element shall also be present. 

That is, exactly one LoadFont element **_must_** be present whenever Text elements are used later in the file. The only time that the LoadFont element can be omitted is when no Text elements are present in the file (i.e. Image elements referencing PNG files are used instead).

Does clairmeta currently perform this test?

**Comment by matmat** [comment]
I have a MXF wrapped XML like this:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<SubtitleReel xmlns="http://www.smpte-ra.org/schemas/428-7/2010/DCST">
    <Id>urn:uuid:...</Id>
    <ContentTitleText>...</ContentTitleText>
    <AnnotationText>DCDM subtitle file</AnnotationText>
    <IssueDate>...</IssueDate>
    <ReelNumber>01</ReelNumber>
    <Language>...</Language>
    <EditRate>24 1</EditRate>
    <TimeCodeRate>24</TimeCodeRate>
    <StartTime>00:00:00:00</StartTime>
    <SubtitleList>
        <Font Color="FFFFFFFF" Weight="normal" Size="45" Effect="border" EffectColor="FF000000" AspectAdjust="1.00">
            <Subtitle SpotNumber="1" TimeIn="00:01:42:01" TimeOut="00:01:47:01" FadeUpTime="00:00:00:00" FadeDownTime="00:00:00:00">
                <Text Valign="bottom" Halign="left" Vposition="18.0" Hposition="10.0" Direction="ltr">...</Text>
                <Text Valign="bottom" Halign="left" Vposition="10.0" Hposition="10.0" Direction="ltr">...</Text>
            </Subtitle>
...
```

Which make Clairmeta crash in the following way because it assumes that there was a LoadFont element with a file reference:

```
2019-03-26 19:52:40,767 - Clairmeta - ERROR - Check unknown error
Traceback (most recent call last):
  File "/home/mhm/ClairMeta/clairmeta/dcp_check_base.py", line 112, in run_check
    check_res = func(*args)
  File "/home/mhm/ClairMeta/clairmeta/dcp_check_subtitle.py", line 301, in check_subtitle_cpl_font
    path, uri = self.st_util.get_font_path(st_dict, folder)
  File "/home/mhm/ClairMeta/clairmeta/dcp_check_subtitle.py", line 140, in get_font_path
    uri = self.get_subtitle_elem(xml_dict, 'LoadFont').lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by matmat** [comment]
Also, it would probably be a good idea to catch the condition when there are Font element(s) with an ID attribute, but no LoadFont element present in the XML file as described here:

https://github.com/wolfgangw/digital_cinema_tools_distribution/issues/15

**Comment by remia** [comment]
Thanks for the report @matmat.

*  You are right, there is currently no check to enforce the one LoadFont constraint for text based SMPTE subtitle. I'll soon push a PR covering this, would be helpful if you could check it on your content as I don't have any SMPTE MXF Subtitles with this issue on hand.
*  The LoadFont related crash is indeed a side effect, Clairmeta try to find the LoadFont element to check that is indeed a corresponding font file wrapped in the MXF, will be fixed
*  On your last point, not exactly sure but I think this is already covered in https://github.com/Ymagis/ClairMeta/blob/develop/clairmeta/dcp_check_subtitle.py#L277, this check find the LoadFont ID and then compare this with all the Font ID elements in the subtitle file.

**Comment by matmat** [comment]
Thanks!

I have tested https://github.com/Ymagis/ClairMeta/pull/84 and it seems to work correctly, I get the following output from the same DCP above:

```	check_subtitle_cpl_loadfont - CPL_377508cd-d170-4842-a361-d8f291e49b84.xml (Asset tt_5cf9db37-7843-4544-8a06-a464eb70feed.mxf) : Text based subtitle shall contain one and only one LoadFont element, found 0
	check_subtitle_cpl_loadfont - CPL_377508cd-d170-4842-a361-d8f291e49b84.xml (Asset tt_b97999c6-7eca-4214-b4f9-192da1689b89.mxf) : Text based subtitle shall contain one and only one LoadFont element, found 0
	check_subtitle_cpl_loadfont - CPL_377508cd-d170-4842-a361-d8f291e49b84.xml (Asset tt_55e215a9-c77b-47d2-8b56-824134ed8f4a.mxf) : Text based subtitle shall contain one and only one LoadFont element, found 0
	check_subtitle_cpl_loadfont - CPL_377508cd-d170-4842-a361-d8f291e49b84.xml (Asset tt_e6280fd8-3b49-47e0-b91b-553a32328fbe.mxf) : Text based subtitle shall contain one and only one LoadFont element, found 0
```

**Comment by remia** [comment]
Thanks, will merge then.
