### ISSUE TITLE
Do DCP:s with encrypted content need be digitally signed?

### ISSUE THREAD

**Issue by matmat** [Ymagis/ClairMeta#91]
Is there an reference for this constraint on Interop DCP:s? 
https://github.com/Ymagis/ClairMeta/blob/develop/clairmeta/dcp_check.py#L157-L172

I can't find one..

**Comment by remia** [comment]
Good question, first of all this check is run only for SMPTE DCPs currently, see https://github.com/Ymagis/ClairMeta/blob/develop/clairmeta/dcp_check.py#L159.

I quickly browsed through the standards and only found related rules in the DCI specification (which should target both SMPTE and Interop I think) :

```
5.3.4.7 Security of the CPL
For encrypted essence, the Composition Playlist shall be digitally signed such that modifications to the Composition Playlist (and/or the associated composition) can be detected. In support of this, the CPL assets "KeyID" and "Hash" elements shall be present in the CPL track file asset structure.
```

```
5.5.2.3. Security (PKL)
The distribution method is required to provide digital signatures to allow the recipient to verify integrity of the Packing List and the enclosed files. In particular, where the DCP contains encrypted essence files, the Packing List shall be digitally signed.
```

So maybe this check should be enforced for all DCPs ?

Side node, I think it would be helpful to provide justification for **all** implemented check by providing a reference to related standard (and maybe quote) in the docstring.

**Comment by kieranjol** [comment]
+1 on the reference to specs in the docstrings.

**Comment by remia** [comment]
Will create a new issue for the code documentation update and close this one if the answer is accepted.
