### ISSUE TITLE
Hash element mandatory in CPL for encrypted essence

### ISSUE THREAD

**Issue by matmat** [Ymagis/ClairMeta#92]
According to ST429-2:2013

> **9.11 Hash Element**
> The ```Hash``` element shall be present in an asset when the ```KeyId``` element is present (i.e., when the referenced Track File is encrypted).

I don't there is a check for this at the moment?

This is obviously only strictly required for SMPTE packages on encrypted track files but I think it would be really useful to ***always*** perform this check, but maybe produce a warning where not strictly mandated by the standards

**Comment by remia** [comment]
We currently have this check that require the `Hash` element to be present if there is a `KeyId`, this is enforced for all compositions (SMPTE or Interop) : https://github.com/Ymagis/ClairMeta/blob/develop/clairmeta/dcp_check_cpl.py#L305

Does that fill your needs ?

**Comment by remia** [comment]
Will close if there is nothing to be done.
